apiVersion: v1
kind: Secret
metadata:
  name: {{ include "as400-jdbc-tester.fullname" . }}-secret
  labels:
    {{- include "as400-jdbc-tester.labels" . | nindent 4 }}
type: Opaque
data:
  JDBC_USERNAME: {{ .Values.jdbc.username | b64enc | quote }}
  JDBC_PASSWORD: {{ .Values.jdbc.password | b64enc | quote }}