apiVersion: v1
kind: Service
metadata:
  name: {{ include "as400-jdbc-tester.fullname" . }}
  labels:
    {{- include "as400-jdbc-tester.labels" . | nindent 4 }}
  {{- if .Values.monitoring.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.monitoring.prometheus.path | quote }}
    prometheus.io/port: {{ .Values.monitoring.prometheus.port | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "as400-jdbc-tester.selectorLabels" . | nindent 4 }}